# Generated by Django 5.0.7 on 2024-08-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_app", "0002_user_full_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.ImageField(upload_to="images/", verbose_name="image"),
        ),
    ]
